Repository woowacourse-teams/2025-estime, pull requests merged in 2025-09, with the labels that each got.

#545 Dev 서버 RDS 연결
  docker-compose.dev.yml
Labels: BE, 🗺 infra

#543 Broken Pipe 에러 로그 무시
  estime-api/src/main/java/com/estime/common/sse/application/SseSender.java
Labels: ✨ feat, BE

#532 dev - prod 간 flyway 쿼리 스크립트 일치화
  estime-api/src/main/resources/db/migration/V2__connected_room_add_channel_id_and_rename_to_platform.sql
Labels: BE, ♻️ refactor

#520 기본적인 메타 데이터를 작성
  frontend/build/plugins/InjectGTMPlugin.js
  frontend/public/index.html
  frontend/public/open-graph-thumbnail.jpg
  frontend/src/index.tsx
  frontend/src/libs/trackers/GTM.ts
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: ✨ feat, FE

#571 feat: lighthouse 정보 pr comment에 달기 (CI 자동화)
  .github/workflows/lighthouse-ci.yml
Labels: ✨ feat, FE

#554 테스트 데이터 생성 스크립트 수정
  estime-api/src/main/resources/db/test/insert_test_data.sh
Labels: 🛠 fix, BE, ✅ test

#578 SSE 에서 발생하는 IllegalStateException 해결
  estime-api/src/main/java/com/estime/common/sse/application/SseConnectionManager.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSender.java
  estime-api/src/main/java/com/estime/common/sse/application/SseService.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSubscriptionManager.java
  estime-api/src/main/java/com/estime/common/sse/domain/SseConnection.java
  estime-api/src/main/java/com/estime/common/sse/domain/SseEmitters.java
  estime-api/src/main/java/com/estime/common/sse/presentation/SseController.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
Labels: 🛠 fix, BE, ♻️ refactor

#536 방 전체 투표 현황 조회 기능 참가자 리스트 추가
  estime-api/src/main/java/com/estime/room/application/dto/output/DateTimeSlotStatisticOutput.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/participant/Participants.java
  estime-api/src/main/java/com/estime/room/presentation/dto/response/DateTimeSlotStatisticResponse.java
  estime-api/src/test/java/com/estime/room/domain/participant/ParticipantsTest.java
Labels: ✨ feat, BE

#582 feat: fallbackUI 추가
  frontend/src/RootElement.tsx
  frontend/src/pages/CheckEvent/components/Skeleton/CheckEventPageSkeleton.styled.ts
  frontend/src/pages/CheckEvent/components/Skeleton/index.tsx
  frontend/src/pages/CreateEvent/Mobile/MobileCreateEventPage.tsx
  frontend/src/pages/CreateEvent/components/Skeleton/CreateEventPageSkeleton.styled.ts
  frontend/src/pages/CreateEvent/components/Skeleton/index.tsx
  frontend/src/pages/common/CreditsPage.tsx
  frontend/src/pages/common/CreditsPageSkeleton.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/components/Skeleton/Shimmer.styled.ts
  frontend/src/shared/components/Skeleton/SkeletonBox.tsx
  frontend/src/shared/components/Spinner/Spinner.styled.ts
  frontend/src/shared/components/Spinner/index.tsx
Labels: ✨ feat, FE

#581 feat: 가장 많이 투표한 시간대를 구현
  frontend/src/pages/CheckEvent/components/Heatmap/HeatMapDataCell/HeatMapDataCell.styled.ts
  frontend/src/pages/CheckEvent/components/Heatmap/HeatMapDataCell/index.tsx
  frontend/src/pages/CheckEvent/components/Heatmap/Heatmap.stories.tsx
  frontend/src/pages/CheckEvent/components/Heatmap/index.tsx
  frontend/src/pages/CheckEvent/components/TableTooltip/TableTooltip.stories.tsx
  frontend/src/pages/CheckEvent/hooks/useHeatmapStatistics.ts
  frontend/src/pages/CheckEvent/utils/getCellColor.ts
  frontend/src/styles/theme.ts
Labels: ✨ feat, FE

#579 chore: createeventpage 잡일들.
  frontend/src/pages/CreateEvent/components/Calendar/DayCell/DayCell.styled.tsx
  frontend/src/shared/layout/Header/Header.styled.tsx
  frontend/src/shared/layout/Header/index.tsx
Labels: ✨ feat, FE

#588 fix: theme import 경로 수정
  frontend/src/pages/CreateEvent/components/Calendar/DayCell/DayCell.styled.tsx
Labels: FE, 🚨 hotfix

#583 refactor: 타임테이블 성능 개선 리펙토링(2안)
  frontend/src/pages/CheckEvent/CheckEventPage.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeSlotColumn/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableCell/TimeTableCell.styled.ts
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableCell/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableColumn/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/index.tsx
  frontend/src/pages/CheckEvent/contexts/TimeSelectionContext.tsx
  frontend/src/pages/CheckEvent/hooks/useCheckRoomSession.ts
  frontend/src/pages/CheckEvent/hooks/useLocalTimeSelection.ts
  frontend/src/pages/CheckEvent/hooks/useSSE.ts
  frontend/src/pages/CheckEvent/hooks/useTimeSelection.ts
  frontend/src/pages/CheckEvent/hooks/useUserAvailability.ts
  frontend/src/pages/CreateEvent/components/BasicSettings/index.tsx
  frontend/src/shared/hooks/common/useCreateError.ts
Labels: FE, ♻️ refactor

#597 Room, Vote 인덱스 추가 및 개선
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/main/java/com/estime/room/domain/participant/Participant.java
  estime-api/src/main/resources/db/migration/V5__alter_table_drop_fk_and_index.sql
  estime-api/src/main/resources/db/migration/V6__add_index_and_alter_vote_composite_key.sql
Labels: ✨ feat, BE

#605 hotfix: og:image name 속성 변경 (property로)
  frontend/public/index.html
  frontend/webpack.common.js
Labels: FE, 🚨 hotfix

#607 fix: 잘못된 폰트 문법 수정
  frontend/src/styles/index.css
Labels: FE, 🚨 hotfix

#608 v1.3.1
  frontend/CHANGELOG.md
  frontend/package.json
  frontend/public/index.html
  frontend/src/pages/CheckEvent/CheckEventPage.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeSlotColumn/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableCell/TimeTableCell.styled.ts
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableCell/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/TimeTableColumn/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/index.tsx
  frontend/src/pages/CheckEvent/contexts/TimeSelectionContext.tsx
  frontend/src/pages/CheckEvent/hooks/useCheckRoomSession.ts
  frontend/src/pages/CheckEvent/hooks/useLocalTimeSelection.ts
  frontend/src/pages/CheckEvent/hooks/useSSE.ts
  frontend/src/pages/CheckEvent/hooks/useTimeSelection.ts
  frontend/src/pages/CheckEvent/hooks/useUserAvailability.ts
  frontend/src/pages/CreateEvent/components/BasicSettings/index.tsx
  frontend/src/shared/hooks/common/useCreateError.ts
  frontend/src/styles/index.css
  frontend/webpack.common.js
Labels: FE

#615 로컬 환경에서의 CORS 오류 해결 및 클라이언트 Origin URL 설정 구조 개선
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
  .github/workflows/CI.yml
  estime-api/src/main/java/com/estime/common/config/ClientOriginProperties.java
  estime-api/src/main/java/com/estime/common/config/WebConfig.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/PlatformShortcutBuilder.java
  estime-api/src/main/resources/application-dev.yml
  estime-api/src/main/resources/application-local.yml
  estime-api/src/main/resources/application-prod.yml
Labels: 🛠 fix, BE, ♻️ refactor
