Repository woowacourse-teams/2025-estime, pull requests merged in 2025-08, with the labels that each got.

#292 spring log 설정 추가
  .gitignore
  docker-compose.yml
  estime-api/src/main/resources/application.yml
Labels: ✨ feat, BE

#261 에러 페이지와 에러 바운더리 작성
  frontend/src/ErrorBoundary.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/pages/ErrorPage.styled.ts
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/styles/ErrorPage.styled.ts
Labels: ✨ feat, FE

#294 마감기한 시간 추가 및 설명 텍스트 크기 수정
  frontend/src/components/CheckEventPageHeader/index.tsx
  frontend/src/components/LoginSuggestModal/index.tsx
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/CalendarSettings/index.tsx
Labels: FE, ♻️ refactor, 💄 design

#300 방 참여 페이지에서 뒤로가기 방지
  frontend/src/pages/CreateEventPage.tsx
Labels: FE, ♻️ refactor

#313 api 서버의 log 파일 저장 위치 수정
  docker-compose.yml
Labels: 🛠 fix, BE

#317 controller parameter 파싱 오류 수정
  estime-api/src/main/java/com/estime/room/presentation/RoomController.java
  estime-api/src/main/java/com/estime/room/presentation/RoomControllerSpecification.java
Labels: 🛠 fix, BE

#328 spring 프로퍼티 설정 내 cloudwatch namespace 수정
  estime-api/src/main/resources/application.yml
Labels: BE, 🗺 infra

#334 cloudwatch 설정 로직 수정 및 추가
  estime-api/build.gradle
  estime-api/src/main/java/com/estime/aws/CloudWatchUtil.java
  estime-api/src/main/resources/application.yml
Labels: BE, 🗺 infra

#332 유틸 함수 테스트 코드 작성
  frontend/src/utils/Calendar/__tests__/dayInMonth.spec.ts
  frontend/src/utils/common/__test__/DateManager.spec.ts
  frontend/src/utils/common/__test__/FormatManager.spec.ts
  frontend/src/utils/common/__test__/TimeManager.spec.ts
Labels: FE, ✅ test

#304 방 생성 시, 버튼 유효성 체크
  frontend/src/components/Button/index.tsx
  frontend/src/components/Sections/BasicSettings/BasicSettings.stories.tsx
  frontend/src/components/Sections/BasicSettings/BasicSettings.styled.ts
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/CalendarSettings/CalendarSettings.styled.ts
  frontend/src/components/Sections/CalendarSettings/index.tsx
  frontend/src/hooks/CreateRoom/useShakeAnimation.tsx
  frontend/src/hooks/useCreateRoom.ts
  frontend/src/pages/CreateEventPage.tsx
  frontend/src/styles/animations/shake.ts
Labels: FE, ♻️ refactor

#335 RoomSession 값 객체로 변경
  estime-api/src/main/java/com/estime/connection/application/dto/input/ConnectedRoomCreateInput.java
  estime-api/src/main/java/com/estime/connection/application/dto/input/ConnectedRoomCreatedMessageInput.java
  estime-api/src/main/java/com/estime/connection/application/dto/output/ConnectedRoomCreateOutput.java
  estime-api/src/main/java/com/estime/connection/domain/ConnectedRoomRepository.java
  estime-api/src/main/java/com/estime/connection/infrastructure/ConnectedRoomJpaRepository.java
  estime-api/src/main/java/com/estime/connection/infrastructure/ConnectedRoomRepositoryImpl.java
  estime-api/src/main/java/com/estime/connection/presentation/dto/request/ConnectedRoomCreateRequest.java
  estime-api/src/main/java/com/estime/connection/presentation/dto/response/ConnectedRoomCreateResponse.java
  estime-api/src/main/java/com/estime/connection/support/ConnectionUrlHelper.java
  estime-api/src/main/java/com/estime/room/application/dto/input/ParticipantCreateInput.java
  estime-api/src/main/java/com/estime/room/application/dto/input/RoomCreateInput.java
  estime-api/src/main/java/com/estime/room/application/dto/input/VotesUpdateInput.java
  estime-api/src/main/java/com/estime/room/application/dto/output/DateTimeSlotStatisticOutput.java
  estime-api/src/main/java/com/estime/room/application/dto/output/RoomCreateOutput.java
  estime-api/src/main/java/com/estime/room/application/dto/output/RoomOutput.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/main/java/com/estime/room/domain/RoomRepository.java
  estime-api/src/main/java/com/estime/room/domain/participant/vote/Vote.java
  estime-api/src/main/java/com/estime/room/domain/participant/vote/VoteId.java
  estime-api/src/main/java/com/estime/room/domain/participant/vote/Votes.java
  estime-api/src/main/java/com/estime/room/domain/slot/vo/DateSlot.java
  estime-api/src/main/java/com/estime/room/domain/slot/vo/DateTimeSlot.java
  estime-api/src/main/java/com/estime/room/domain/slot/vo/TimeSlot.java
  estime-api/src/main/java/com/estime/room/domain/vo/RoomSession.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomJpaRepository.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomRepositoryImpl.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomSessionGenerator.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/DateSlotConverter.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/DateTimeSlotConverter.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/RoomSessionConverter.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/TimeSlotConverter.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/TsidConverter.java
  estime-api/src/main/java/com/estime/room/presentation/RoomController.java
  estime-api/src/main/java/com/estime/room/presentation/RoomControllerSpecification.java
  estime-api/src/main/java/com/estime/room/presentation/dto/request/ParticipantCreateRequest.java
  estime-api/src/main/java/com/estime/room/presentation/dto/request/ParticipantVotesUpdateRequest.java
  estime-api/src/main/java/com/estime/room/presentation/dto/request/RoomCreateRequest.java
  estime-api/src/main/java/com/estime/room/presentation/dto/response/RoomCreateResponse.java
  estime-api/src/main/java/com/estime/room/presentation/dto/response/RoomResponse.java
  estime-api/src/test/java/com/estime/connection/application/ConnectedRoomApplicationServiceTest.java
  estime-api/src/test/java/com/estime/room/application/service/RoomApplicationServiceTest.java
  estime-api/src/test/java/com/estime/room/domain/participant/vote/VotesTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/DateSlotTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/DateTimeSlotTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/TimeSlotTest.java
Labels: ✨ feat, BE

#342 닉네임 중복 여부 구분 모달 추가
  frontend/src/apis/room/room.ts
  frontend/src/apis/room/type.ts
  frontend/src/apis/time/type.ts
  frontend/src/components/EntryConfirmModal/EntryConfirmModal.styled.ts
  frontend/src/components/EntryConfirmModal/index.tsx
  frontend/src/components/LoginModal/LoginModal.stories.tsx
  frontend/src/components/LoginModal/index.tsx
  frontend/src/components/Timetable/TimeTableCell/TimeTableCell.styled.ts
  frontend/src/hooks/Login/useUserLogin.ts
  frontend/src/hooks/TimeTableRoom/useModalControl.ts
  frontend/src/hooks/useUserAvailability.ts
  frontend/src/pages/CheckEventPage.tsx
Labels: ✨ feat, FE, 🚨 hotfix

#340 토스트 UI 구현
  frontend/src/components/Layout/ToastZone/ToastZone.styled.ts
  frontend/src/components/Layout/ToastZone/index.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/StatusIcon/StatusIcon.styled.ts
  frontend/src/components/StatusIcon/index.tsx
  frontend/src/components/Toast/Toast.stories.tsx
  frontend/src/components/Toast/Toast.styled.ts
  frontend/src/components/Toast/index.tsx
  frontend/src/contexts/ToastContext.ts
  frontend/src/hooks/useUserAvailability.ts
  frontend/src/icons/IError.tsx
  frontend/src/icons/ISuccess.tsx
  frontend/src/icons/IWarning.tsx
  frontend/src/providers/ToastProvider.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/toastType.ts
Labels: ✨ feat, FE

#350 Timetable, Heatmap 플립 애니메이션 추가
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/pages/styles/CheckEventPage.styled.ts
Labels: ✨ feat, FE

#355 3차 데모 이전 hotfix PR
  frontend/src/pages/CreateEventPage.tsx
Labels: FE, 🚨 hotfix

#365 docker-compose dev, prod 로그 디렉터리 경로 오류 수정
  docker-compose-prod.yml
  docker-compose.dev.yml
Labels: BE, 🗺 infra, 🚨 hotfix

#371 dev, prod 환경 설정 수정
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
  estime-api/src/main/resources/application-common.yml
  estime-api/src/main/resources/application-dev.yml
  estime-api/src/main/resources/application-local.yml
  estime-api/src/main/resources/application-prod.yml
Labels: ✨ feat, BE, 🗺 infra

#375 prod용 docker-compose api 컨테이너의 mysql 컨테이너 의존성 잔류 코드 제거
  docker-compose.prod.yml
Labels: BE, 🗺 infra, 🚨 hotfix

#387 모바일 시작 페이지 작업
  frontend/src/components/Layout/Header/Header.styled.tsx
  frontend/src/components/Layout/Header/index.tsx
  frontend/src/icons/IEstimeIcon.tsx
  frontend/src/icons/IEstimeLogo.tsx
  frontend/src/icons/Logo.tsx
  frontend/src/pages/Mobile/MobileCreateEventPage.tsx
  frontend/src/pages/styles/MobileCreateEventPage.styled.ts
Labels: ✨ feat, FE

#400 Room 단위 SSE 연결 구현
  estime-api/src/main/java/com/estime/common/sse/application/service/SseSubscriptionManager.java
  estime-api/src/main/java/com/estime/common/sse/domain/SseEmitters.java
  estime-api/src/main/java/com/estime/common/sse/presentation/SseController.java
  estime-api/src/main/java/com/estime/common/sse/presentation/dto/SseInitMessage.java
  estime-api/src/main/resources/application-dev.yml
  estime-api/src/main/resources/application-local.yml
  estime-api/src/main/resources/application-prod.yml
Labels: ✨ feat, BE

#379 디스코드 서버 에러 로그 구현
  estime-api/build.gradle
  estime-api/src/main/java/com/estime/common/exception/GlobalExceptionHandler.java
  estime-api/src/main/java/com/estime/common/logging/ApiLogFilter.java
  estime-api/src/main/java/com/estime/common/logging/MdcKey.java
  estime-api/src/main/resources/application-common.yml
  estime-api/src/main/resources/application-dev.yml
  estime-api/src/main/resources/application-prod.yml
  estime-api/src/main/resources/logback.xml
Labels: ✨ feat, BE

#393 모바일 버전 방 생성 페이지
  frontend/src/App.tsx
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Input/Input.styled.ts
  frontend/src/components/Layout/Layout.styled.ts
  frontend/src/components/Sections/BasicSettings/BasicSettings.styled.ts
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/CalendarSettings/CalendarSettings.styled.ts
  frontend/src/components/Timepicker/Timepicker.styled.ts
  frontend/src/components/Timepicker/index.tsx
  frontend/src/hooks/Mobile/useIsMobile.ts
  frontend/src/pages/Mobile/MobileCreateEventPage.tsx
  frontend/src/pages/styles/MobileCreateEventPage.styled.ts
  frontend/src/routes/DesktopRoutes.tsx
  frontend/src/routes/MobileRoutes.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.d.ts
Labels: ✨ feat, FE

#401 마감기한 이후 편집 불가능하도록 수정
  estime-api/src/main/java/com/estime/common/exception/domain/DeadlineOverdueException.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/test/java/com/estime/room/domain/RoomTest.java
Labels: ✨ feat, BE, ✅ test

#408 방에서 선택 불가능한 타임슬롯에 대한 요청 예외 처리
  estime-api/src/main/java/com/estime/common/exception/domain/UnavailableSlotException.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/main/java/com/estime/room/domain/slot/vo/DateTimeSlot.java
  estime-api/src/test/java/com/estime/room/application/service/RoomApplicationServiceTest.java
Labels: ✨ feat, BE

#423 최신 배포 버전이 노출되도록 설정
  frontend/build/plugins/InjectVersionConsolePlugin.js
  frontend/build/utils/buildMeta.js
  frontend/src/components/Text/Text.styled.ts
  frontend/src/components/Text/index.tsx
  frontend/webpack.common.js
Labels: ✨ feat, FE, 🗺 infra

#418 카카오톡으로 공유하기 기능 추가
  frontend/public/index.html
  frontend/src/components/Button/Button.styled.ts
  frontend/src/components/Button/index.tsx
  frontend/src/components/CheckEventPageHeader/index.tsx
  frontend/src/components/CopyLinkButton/CopyLinkButton.styled.ts
  frontend/src/components/CopyLinkButton/index.tsx
  frontend/src/components/CopyLinkModal/CopyLinkModal.styled.ts
  frontend/src/components/CopyLinkModal/index.tsx
  frontend/src/components/KakaoShareButton/index.tsx
  frontend/src/components/Layout/ToastZone/ToastZone.styled.ts
  frontend/src/components/Modal/Modal.styled.ts
  frontend/src/components/ShareButton/index.tsx
  frontend/src/constants/styles.ts
  frontend/src/hooks/TimeTableRoom/useModalControl.ts
  frontend/src/hooks/useKakaoInit.ts
  frontend/src/icons/IChat.tsx
  frontend/src/icons/ICheck.tsx
  frontend/src/icons/ICopy.tsx
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/global.d.ts
Labels: ✨ feat, FE

#438 CD 스크립트에 기존 .env 파일 백업 스크립트 추가
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
Labels: ✨ feat, BE, 🗺 infra

#416 마감기한 관련 함수 수정
  frontend/src/components/Heatmap/Heatmap.stories.tsx
  frontend/src/hooks/Error/useCreateError.ts
  frontend/src/hooks/TimeTableRoom/useModalControl.ts
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/utils/common/DateManager.ts
  frontend/src/utils/common/TimeManager.ts
  frontend/src/utils/common/__test__/DateManager.spec.ts
  frontend/src/utils/common/__test__/TimeManager.spec.ts
  frontend/src/utils/getWeight.ts
Labels: 🛠 fix, FE

#447 배포시, 커밋해시 및 커밋메시지 확인 수정
  frontend/buildspec.yml
Labels: FE, 🗺 infra, ✅ test

#420 모바일 타임테이블(히트맵) 페이지네이션
  frontend/src/apis/transform/toCreateRoomInfo.ts
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/AccordionToggleButton/AccordionToggleButton.styled.ts
  frontend/src/components/AccordionToggleButton/index.tsx
  frontend/src/components/Calendar/CalendarButton/CalendarButton.tsx
  frontend/src/components/Calendar/DayCell/DayCell.styled.tsx
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/DatePicker/DatePicker.styled.ts
  frontend/src/components/Heatmap/Heatmap.styled.ts
  frontend/src/components/Heatmap/index.tsx
  frontend/src/components/Input/Input.styled.ts
  frontend/src/components/MobileTimeTablePageButtons/index.tsx
  frontend/src/components/PageArrowButton/index.tsx
  frontend/src/components/PageArrowButton/pageArrowButton.styled.tsx
  frontend/src/components/TimeTableHeader/TimeTableHeader.styled.ts
  frontend/src/components/Timepicker/Timepicker.styled.ts
  frontend/src/components/Timetable/Timetable.styled.ts
  frontend/src/components/Timetable/index.tsx
  frontend/src/hooks/Pagination/usePagination.ts
  frontend/src/hooks/Pagination/useTimeTablePagination.ts
  frontend/src/pages/CheckEventPage.tsx
Labels: ✨ feat, FE

#469 논리 삭제 (soft delete) 적용, 조회 시 active 검증 추가
  estime-api/src/main/java/com/estime/common/BaseEntity.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomJpaRepository.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomRepositoryImpl.java
  estime-api/src/main/java/com/estime/room/infrastructure/participant/ParticipantJpaRepository.java
  estime-api/src/main/java/com/estime/room/infrastructure/participant/ParticipantRepositoryImpl.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/PlatformJpaRepository.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/PlatformRepositoryImpl.java
  estime-api/src/main/resources/db/migration/V3__add_active_column.sql
Labels: ✨ feat, BE

#449 GTM을 prod 환경에서만 실행하게 설정
  frontend/public/index.html
  frontend/src/index.tsx
  frontend/src/utils/common/gtm.ts
  frontend/webpack.prod.js
Labels: ✨ feat, FE

#445 앙구 일구 버그 fix
  frontend/src/components/LoginModal/index.tsx
  frontend/src/components/Modal/FocusTrap.tsx
  frontend/src/hooks/Login/useUserLogin.ts
  frontend/src/pages/CheckEventPage.tsx
Labels: 🛠 fix, FE

#475 연동된 디스코드 방에 알림 보내기
  frontend/src/apis/common/constant.ts
  frontend/src/apis/room/type.ts
  frontend/src/components/Check/Check.styled.ts
  frontend/src/components/Check/index.tsx
  frontend/src/components/Layout/Header/index.tsx
  frontend/src/components/NotificationModal/NotificationModal.styled.ts
  frontend/src/components/NotificationModal/index.tsx
  frontend/src/components/PlatformLogo/index.tsx
  frontend/src/hooks/useCreateRoom.ts
  frontend/src/pages/CreateEventPage.tsx
  frontend/src/pages/Mobile/MobileCreateEventPage.tsx
Labels: ✨ feat, FE

#482 투표 리마인드(독려) 및 데드라인(마감) 디스코드 알림을 위한 스케줄러 추가
  estime-api/src/main/java/com/estime/common/DomainTerm.java
  estime-api/src/main/java/com/estime/common/exception/GlobalExceptionHandler.java
  estime-api/src/main/java/com/estime/common/presentation/RootController.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSender.java
  estime-api/src/main/java/com/estime/notification/application/NotificationService.java
  estime-api/src/main/java/com/estime/room/application/RoomDeadlineScheduler.java
  estime-api/src/main/java/com/estime/room/application/dto/input/ConnectedRoomCreateInput.java
  estime-api/src/main/java/com/estime/room/application/dto/input/RoomCreateInput.java
  estime-api/src/main/java/com/estime/room/application/dto/input/RoomSessionInput.java
  estime-api/src/main/java/com/estime/room/application/dto/input/VotesFindInput.java
  estime-api/src/main/java/com/estime/room/application/dto/output/RoomOutput.java
  estime-api/src/main/java/com/estime/room/application/vo/NotificationTask.java
  estime-api/src/main/java/com/estime/room/application/vo/NotificationTaskType.java
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/main/java/com/estime/room/domain/RoomRepository.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformCommand.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformMessage.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomJpaRepository.java
  estime-api/src/main/java/com/estime/room/infrastructure/RoomRepositoryImpl.java
  estime-api/src/main/java/com/estime/room/infrastructure/converter/TsidConverter.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordGuildJoinMessageRegistrar.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordMessageBuilder.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordMessageSender.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordSlashCommandListener.java
  estime-api/src/main/java/com/estime/room/presentation/dto/request/ConnectedRoomCreateRequest.java
  estime-api/src/main/java/com/estime/room/presentation/dto/request/RoomCreateRequest.java
  estime-api/src/main/java/com/estime/room/presentation/dto/response/RoomResponse.java
  estime-api/src/test/java/com/estime/room/application/RoomDeadlineSchedulerTest.java
  estime-api/src/test/java/com/estime/room/application/service/RoomApplicationServiceTest.java
  estime-api/src/test/java/com/estime/room/domain/RoomTest.java
Labels: ✨ feat, BE, ♻️ refactor

#484 안내 문구 제거 완료
  frontend/src/pages/CreateEventPage.tsx
Labels: ✨ feat, FE

#474 prod 서버 rollback 스크립트 추가
  .github/workflows/rollback-prod.yml
Labels: ✨ feat, BE, 🗺 infra

#493 api 서버 Dockerfile 시간대 설정 추가
  estime-api/Dockerfile
Labels: ✨ feat, BE, 🗺 infra

#491 롤백 테스트용 commit
  estime-api/src/test/java/com/estime/EstimeApiApplicationTests.java
Labels: BE, 🗺 infra, ✅ test

#496 스케줄링 동작 설정
  estime-api/src/main/java/com/estime/EstimeApiApplication.java
Labels: ✨ feat, BE

#495 SSE 연결 관리 방식 개선
  estime-api/src/main/java/com/estime/common/exception/GlobalExceptionHandler.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSender.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSubscriptionManager.java
Labels: BE, ♻️ refactor

#498 release v1.0.0-be
  .github/workflows/CD-prod.yml
  estime-api/Dockerfile
  estime-api/src/main/java/com/estime/EstimeApiApplication.java
  estime-api/src/main/java/com/estime/common/exception/GlobalExceptionHandler.java
  estime-api/src/main/java/com/estime/common/logging/ApiLogFilter.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSender.java
  estime-api/src/main/java/com/estime/common/sse/application/SseSubscriptionManager.java
  estime-api/src/test/java/com/estime/EstimeApiApplicationTests.java
Labels: ✨ feat, BE

#503 Platform과 연결되지 않은 Room에 독려/마감 알림 전송 시도 삭제
  estime-api/src/main/java/com/estime/room/application/RoomDeadlineScheduler.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformNotification.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformNotificationType.java
  estime-api/src/test/java/com/estime/room/application/RoomDeadlineSchedulerTest.java
Labels: 🛠 fix, BE

#506 release v1.0.1-be
  estime-api/src/main/java/com/estime/notification/application/NotificationService.java
  estime-api/src/main/java/com/estime/room/application/RoomDeadlineScheduler.java
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformNotification.java
  estime-api/src/main/java/com/estime/room/domain/platform/PlatformNotificationType.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/PlatformShortcutBuilder.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordMessageBuilder.java
  estime-api/src/main/java/com/estime/room/infrastructure/platform/discord/DiscordMessageSender.java
  estime-api/src/test/java/com/estime/room/application/RoomDeadlineSchedulerTest.java
Labels: BE, 🗺 infra

#511 과거 `DateSlot`을 가진 `Room` 조회 불가 문제 해결
  estime-api/src/main/java/com/estime/room/application/service/RoomApplicationService.java
  estime-api/src/main/java/com/estime/room/domain/Room.java
  estime-api/src/main/java/com/estime/room/domain/slot/vo/DateSlot.java
  estime-api/src/test/java/com/estime/room/application/RoomDeadlineSchedulerTest.java
  estime-api/src/test/java/com/estime/room/application/service/RoomApplicationServiceTest.java
  estime-api/src/test/java/com/estime/room/domain/RoomTest.java
  estime-api/src/test/java/com/estime/room/domain/participant/vote/VotesTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/DateSlotTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/DateTimeSlotTest.java
  estime-api/src/test/java/com/estime/room/domain/vo/TimeSlotTest.java
Labels: 🛠 fix, BE
