Repository woowacourse-teams/2025-estime, pull requests merged in 2025-10, with the labels that each got.

#620 도커 이미지 내부 권한 문제 해결
  Dockerfile
Labels: 🛠 fix, BE

#621 Prepare log directory for deployment
  .github/workflows/CD-dev.yml
Labels: 🛠 fix, BE, 🗺 infra

#626 nginx 검증 로직 수정
  .github/workflows/CD-prod.yml
Labels: 🛠 fix, BE, 🚢 release

#627 블루-그린 배포 스크립트 오류 수정
  .github/workflows/CD-prod.yml
Labels: BE, 🚢 release

#629 fix: 타임존 설정
  Dockerfile
Labels: 🛠 fix, BE, 🗺 infra

#631 release v1.0.8-be
  Dockerfile
  application/src/main/java/com/estime/room/presentation/dto/response/DateTimeSlotStatisticResponse.java
Labels: 🛠 fix, BE, 🚢 release

#633 refactor: createEventPage 리펙터
  frontend/src/apis/transform/toCreateRoomInfo.ts
  frontend/src/constants/initialRoomInfo.ts
  frontend/src/pages/CreateEvent/CreateEventPage.tsx
  frontend/src/pages/CreateEvent/Mobile/MobileCreateEventPage.tsx
  frontend/src/pages/CreateEvent/components/BasicSettings/BasicSettings.stories.tsx
  frontend/src/pages/CreateEvent/components/BasicSettings/index.tsx
  frontend/src/pages/CreateEvent/components/Calendar/index.tsx
  frontend/src/pages/CreateEvent/components/CalendarSettings/index.tsx
  frontend/src/pages/CreateEvent/components/NotificationModal/index.tsx
  frontend/src/pages/CreateEvent/hooks/useCreateRoom.ts
  frontend/src/pages/CreateEvent/hooks/useCreateRoomController.ts
  frontend/src/pages/CreateEvent/hooks/useCreateRoomValidation.ts
  frontend/src/pages/CreateEvent/hooks/useMobileCreateRoomController.ts
  frontend/src/pages/CreateEvent/hooks/useMobileCreateRoomValidation.ts
  frontend/src/pages/CreateEvent/store/createRoomStore.ts
  frontend/src/pages/CreateEvent/types/roomInfo.ts
  frontend/src/pages/CreateEvent/utils/CreateRoomValidator.ts
Labels: FE, ♻️ refactor

#635 refactor: checkEventPage 리펙터
  frontend/src/pages/CheckEvent/CheckEventPage.styled.ts
  frontend/src/pages/CheckEvent/CheckEventPage.tsx
  frontend/src/pages/CheckEvent/components/CheckEventPageHeader/index.tsx
  frontend/src/pages/CheckEvent/components/EntryConfirmModal/index.tsx
  frontend/src/pages/CheckEvent/components/Heatmap/HeatMapDataCell/index.tsx
  frontend/src/pages/CheckEvent/components/Heatmap/Heatmap.stories.tsx
  frontend/src/pages/CheckEvent/components/LoginModal/LoginModal.stories.tsx
  frontend/src/pages/CheckEvent/components/LoginModal/index.tsx
  frontend/src/pages/CheckEvent/components/TimeTableHeader/index.tsx
  frontend/src/pages/CheckEvent/components/Timetable/index.tsx
  frontend/src/pages/CheckEvent/components/Tooltip/index.tsx
  frontend/src/pages/CheckEvent/contexts/TimeSelectionContext.tsx
  frontend/src/pages/CheckEvent/hooks/useCheckEventHandlers.ts
  frontend/src/pages/CheckEvent/hooks/useCheckRoomSession.ts
  frontend/src/pages/CheckEvent/hooks/useHeatmapStatistics.ts
  frontend/src/pages/CheckEvent/hooks/useLocalTimeSelection.ts
  frontend/src/pages/CheckEvent/hooks/useSSE.ts
  frontend/src/pages/CheckEvent/hooks/useTimeTablePagination.ts
  frontend/src/pages/CheckEvent/hooks/useUserAvailability.ts
  frontend/src/pages/CheckEvent/hooks/useUserLogin.ts
  frontend/src/pages/CheckEvent/provider/RoomStatisticsProvider.tsx
  frontend/src/pages/CheckEvent/reducers/modalReducer.ts
  frontend/src/pages/CheckEvent/reducers/modeReducer.ts
  frontend/src/pages/CheckEvent/sections/HeatmapSection.tsx
  frontend/src/pages/CheckEvent/sections/Section.styled.ts
  frontend/src/pages/CheckEvent/sections/TimeTableSection.tsx
  frontend/src/pages/CheckEvent/stores/roomStatisticsStore.ts
  frontend/src/pages/CheckEvent/stores/userAvailabilityStore.ts
  frontend/src/pages/CheckEvent/stores/userNameStore.ts
  frontend/src/shared/hooks/common/useFetch.ts
Labels: FE, ♻️ refactor

#651 chore: frontend 아키텍쳐 그림 추가
  README.md
Labels: 🗺 infra
