Repository woowacourse-teams/2025-estime, pull requests merged in 2025-07, with the labels that each got.

#4 개발 환경 설정
  .gitattributes
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/resources/application.yml
Labels: enhancement, BE

#10 로컬/도커 환경 환경 변수 분리
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/src/main/resources/application.yml
Labels: duplicate, BE

#12 TimeSlot 조회 엔드포인트 추가
  backend/src/main/java/com/bether/bether/room/domain/Room.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/input/TimeSlotInput.java
  backend/src/main/java/com/bether/bether/timeslot/application/service/TimeSlotService.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlot.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotRepository.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotJpaRepository.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotRepositoryImpl.java
  backend/src/main/java/com/bether/bether/timeslot/presentation/TimeSlotController.java
  backend/src/main/java/com/bether/bether/timeslot/presentation/dto/request/TimeSlotCreateRequest.java
  backend/src/main/java/com/bether/bether/timeslot/presentation/dto/response/TotalTimeSlotResponse.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotServiceTest.java
Labels: enhancement, BE

#24 [BE] TimeSlot 엔티티 독립 관리 구조를 제거, Room 엔티티 종속 구조로 전환
  backend/src/main/java/com/bether/bether/room/application/service/RoomService.java
  backend/src/main/java/com/bether/bether/room/domain/RoomRepository.java
  backend/src/main/java/com/bether/bether/room/infrastructure/RoomJpaRepository.java
  backend/src/main/java/com/bether/bether/room/infrastructure/RoomRepositoryImpl.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/request/TimeSlotCreateRequest.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TimeSlotStatisticResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TotalTimeSlotResponse.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/input/TimeSlotInput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/input/TimeSlotRankInput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/output/TimeSlotParticipantsOutput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/output/TimeSlotStatisticOutput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/output/TotalTimeSlotRankOutput.java
  backend/src/main/java/com/bether/bether/timeslot/application/service/TimeSlotRankService.java
  backend/src/main/java/com/bether/bether/timeslot/application/service/TimeSlotService.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlot.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotCount.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotParticipants.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotRepository.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotStatistic.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TotalTimeSlotCount.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotJpaRepository.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotRepositoryImpl.java
  backend/src/main/java/com/bether/bether/timeslot/presentation/TimeSlotController.java
  backend/src/main/java/com/bether/bether/timeslot/presentation/dto/response/TotalTimeSlotRankResponse.java
  backend/src/test/java/com/bether/bether/room/application/service/RoomServiceTest.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotRankServiceTest.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotServiceTest.java
Labels: enhancement, BE

#42 [BE] api 경로 내 버전 명시
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
Labels: enhancement, BE

#48 [BE] be/dev, main 병합
  .gitignore
  backend/.gitattributes
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/bether/bether/BetherApplication.java
  backend/src/main/java/com/bether/bether/common/ApiResponse.java
  backend/src/main/java/com/bether/bether/common/BaseEntity.java
  backend/src/main/java/com/bether/bether/common/NotFoundException.java
  backend/src/main/java/com/bether/bether/discord/application/service/DiscordService.java
  backend/src/main/java/com/bether/bether/discord/application/service/DiscordSlashCommandListener.java
  backend/src/main/java/com/bether/bether/discord/application/service/DiscordSlashCommandRegistrar.java
  backend/src/main/java/com/bether/bether/discord/config/DiscordConfig.java
  backend/src/main/java/com/bether/bether/room/application/dto/RoomInput.java
  backend/src/main/java/com/bether/bether/room/application/dto/RoomOutput.java
  backend/src/main/java/com/bether/bether/room/application/service/RoomService.java
  backend/src/main/java/com/bether/bether/room/domain/Room.java
  backend/src/main/java/com/bether/bether/room/domain/RoomRepository.java
  backend/src/main/java/com/bether/bether/room/infrastructure/RoomJpaRepository.java
  backend/src/main/java/com/bether/bether/room/infrastructure/RoomRepositoryImpl.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/request/RoomCreateRequest.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/request/TimeSlotCreateRequest.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/RoomCreateResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TimeSlotStatisticResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TotalTimeSlotResponse.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/input/TimeSlotInput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/output/TimeSlotParticipantsOutput.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/output/TimeSlotStatisticOutput.java
  backend/src/main/java/com/bether/bether/timeslot/application/service/TimeSlotService.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlot.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotParticipants.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotRepository.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotStatistic.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotJpaRepository.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotRepositoryImpl.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/bether/bether/BetherApplicationTests.java
  backend/src/test/java/com/bether/bether/room/application/service/RoomServiceTest.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotServiceTest.java
Labels: enhancement, BE

#47 [BUILD FAIL] [BUILD FAIL] [BUILD FAIL] [BE] CI 파일 추가
  .github/workflows/CI.yml
Labels: enhancement, BE

#51 [FE] 다크 및 라이트 테마 구현
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.d.ts
Labels: enhancement, FE

#53 [BE] AWS EC2 배포 전까지의 CD 과정 진행
  .github/workflows/CD.yml
Labels: enhancement, BE

#54 [BE] AWS EC2 배포 전까지의 CD 과정 진행
  .github/workflows/CD.yml
Labels: enhancement, BE

#44 [BE] Swagger UI 연동 및 API 문서화
  backend/build.gradle
  backend/src/main/java/com/bether/bether/common/ApiResponse.java
  backend/src/main/java/com/bether/bether/common/CustomApiResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomControllerSpecification.java
  backend/src/main/resources/application.yml
Labels: enhancement, BE

#58 input 컴포넌트 구현
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.styled.ts
  frontend/src/components/Input/index.tsx
Labels: enhancement, FE

#63 크로마틱 연동
  .github/workflows/chromatic.yml
  frontend/package-lock.json
  frontend/package.json
Labels: FE

#62 Text 컴포넌트 구현
  frontend/src/components/Text/Text.stories.tsx
  frontend/src/components/Text/Text.styled.tsx
  frontend/src/components/Text/index.tsx
  frontend/src/styles/theme.ts
Labels: enhancement, FE

#68 CD 배포 스크립트 추가
  .github/workflows/CD.yml
Labels: enhancement, BE

#71 docker-compose 환경 별 분리
  backend/docker-compose.dev.yml
  backend/docker-compose.local.yml
  backend/docker-compose.yml
Labels: enhancement, BE

#74 CD 파일 오탈자 수정
  .github/workflows/CD.yml
Labels: bug, BE

#75 CD 작업 경로 수정
  .github/workflows/CD.yml
Labels: bug, BE

#82 feat: app/db port 분리
  backend/docker-compose.dev.yml
  backend/docker-compose.local.yml
  backend/docker-compose.yml
Labels: enhancement, BE

#67 DatePicker 컴포넌트 생성
  frontend/src/components/DatePicker/DatePicker.stories.tsx
  frontend/src/components/DatePicker/DatePicker.styled.ts
  frontend/src/components/DatePicker/index.tsx
Labels: enhancement, FE

#94 CI/CD 관련 스크립트 be/dev 브랜치로 이동
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  backend/Dockerfile
  backend/docker-compose.dev.yml
  backend/docker-compose.local.yml
  backend/docker-compose.yml
Labels: enhancement, BE

#100 CI/CD 관련 스크립트 dev 브랜치로 이동: add short sha step
  .github/workflows/CD.yml
Labels: 🛠 fix, BE, 🗺 infra

#101 CD 파일 중복 코드 삭제
  .github/workflows/CD.yml
Labels: 🛠 fix, BE, 🗺 infra

#104 theme default color 수정
  frontend/src/components/Calendar/Calendar.styled.tsx
  frontend/src/components/Timepicker/Timepicker.styled.ts
  frontend/src/styles/theme.ts
Labels: 🎨 design

#96 크로마틱 CD가 fe/dev에 PR을 날릴시 바로 수정되게 설정.
  .github/workflows/chromatic.yml
Labels: FE

#92 Accodion 컴포넌트 구현
  frontend/public/down-arrow.svg
  frontend/src/components/Accordian/Accordian.stories.tsx
  frontend/src/components/Accordian/Accordian.styled.ts
  frontend/src/components/Accordian/index.tsx
  frontend/src/styles/index.css
Labels: ✨ feat, FE

#109 Storybook 일부 변수 오류
  frontend/.storybook/main.ts
  frontend/tsconfig.json
Labels: 🛠 fix, FE

#114 공통 컴포넌트 스타일 수정 및 추가
  frontend/src/components/Accordian/Accordian.styled.ts
  frontend/src/components/DatePicker/DatePicker.styled.ts
  frontend/src/components/Radio/Radio.styled.ts
  frontend/src/components/Toggle/Toggle.styled.ts
Labels: 🛠 fix, FE, 🎨 design

#117 OptionSettings 컴포넌트 구현
  frontend/src/components/DatePicker/index.tsx
  frontend/src/components/section/OptionSettings/OptionSettings.stories.tsx
  frontend/src/components/section/OptionSettings/OptionSettings.styled.ts
  frontend/src/components/section/OptionSettings/index.tsx
  frontend/src/constants/optionsettings.tsx
  frontend/src/icons/Globe.tsx
  frontend/src/icons/Lock.tsx
  frontend/src/types/iconType.ts
Labels: ✨ feat, FE

#121 calender 리펙터링
  frontend/src/components/Calendar/Calendar.stories.tsx
  frontend/src/components/Calendar/Calendar.styled.tsx
  frontend/src/components/Calendar/DayCell/DayCell.styled.tsx
  frontend/src/components/Calendar/DayCell/index.tsx
  frontend/src/components/Calendar/__tests__/DayCell.spec.tsx
  frontend/src/components/Calendar/index.tsx
  frontend/src/hooks/Calendar/useCalender.tsx
  frontend/src/hooks/Calendar/useDateSelection.tsx
  frontend/src/hooks/Calendar/useDayState.ts
Labels: FE

#122 컴포넌트 디자인 디테일 수정
  frontend/src/components/Accordion/Accordion.stories.tsx
  frontend/src/components/Accordion/Accordion.styled.ts
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/Button/Button.styled.ts
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/DatePicker/DatePicker.styled.ts
  frontend/src/components/Input/Input.styled.ts
  frontend/src/components/Section/BasicSettings/BasicSettings.stories.tsx
  frontend/src/components/Text/Text.styled.ts
  frontend/src/components/Timepicker/index.tsx
  frontend/src/components/section/OptionSettings/OptionSettings.styled.ts
  frontend/src/components/section/OptionSettings/index.tsx
  frontend/src/constants/optionsettings.ts
Labels: 🛠 fix, FE, 🎨 design

#139 session 기반 룸 정보 조회 API 추가
  backend/src/main/java/com/bether/bether/room/application/dto/RoomCreateInput.java
  backend/src/main/java/com/bether/bether/room/application/dto/RoomCreateOutput.java
  backend/src/main/java/com/bether/bether/room/application/dto/RoomOutput.java
  backend/src/main/java/com/bether/bether/room/application/service/RoomService.java
  backend/src/main/java/com/bether/bether/room/domain/Room.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomControllerSpecification.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/request/RoomCreateRequest.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/RoomCreateResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/RoomResponse.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlot.java
  backend/src/test/java/com/bether/bether/room/application/service/RoomServiceTest.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotServiceTest.java
Labels: ✨ feat, BE

#158 TimeSlots 일급 컬렉션 구현
  backend/src/main/java/com/bether/bether/room/application/service/RoomService.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TotalTimeSlotResponse.java
  backend/src/main/java/com/bether/bether/timeslot/application/dto/input/TimeSlotInput.java
  backend/src/main/java/com/bether/bether/timeslot/application/service/TimeSlotService.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotRepository.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlotStatistic.java
  backend/src/main/java/com/bether/bether/timeslot/domain/TimeSlots.java
  backend/src/main/java/com/bether/bether/timeslot/infrastructure/TimeSlotRepositoryImpl.java
  backend/src/test/java/com/bether/bether/timeslot/application/service/TimeSlotServiceTest.java
Labels: ✨ feat, BE

#167 svg 컴포넌트 카멜케이스 변경
  frontend/src/icons/IArrow.tsx
  frontend/src/icons/IChevronLeft.tsx
  frontend/src/icons/IChevronRight.tsx
  frontend/src/icons/IClock.tsx
  frontend/src/icons/IMoon.tsx
  frontend/src/icons/ISun.tsx
  frontend/src/icons/Logo.tsx
Labels: 🛠 fix, FE

#174 Swagger API 문서 수정
  backend/src/main/java/com/bether/bether/room/presentation/RoomControllerSpecification.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/RoomResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TimeSlotRecommendationsResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TimeSlotStatisticResponse.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TotalTimeSlotResponse.java
Labels: ✨ feat, BE

#161 Wrapper 컴포넌트 padding 추가
  frontend/src/components/Layout/Wrapper/Wrapper.styled.ts
  frontend/src/components/Layout/Wrapper/index.tsx
Labels: ✨ feat, FE, ♻️ refactor

#168 방 생성 페이지 상태 관리
  frontend/src/components/Sections/BasicSettings/BasicSettings.stories.tsx
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/CalendarSettings/index.tsx
  frontend/src/components/Sections/OptionSettings/OptionSettings.stories.tsx
  frontend/src/components/Sections/OptionSettings/index.tsx
  frontend/src/components/Timepicker/index.tsx
  frontend/src/constants/optionsettings.ts
  frontend/src/hooks/useCreateRoom.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/hooks/useTimePicker.ts
  frontend/src/pages/CreateEventPage.tsx
  frontend/src/types/field.ts
Labels: ✨ feat, FE

#175 BasicSettings Icon 색상 변경
  frontend/src/components/Sections/BasicSettings/BasicSettings.styled.ts
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/CalendarSettings/index.tsx
  frontend/src/utils/changeIconColor.ts
Labels: FE, 🎨 design

#189 환경 별 URL 분리
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  backend/src/main/java/com/bether/bether/common/config/WebConfig.java
  backend/src/main/java/com/bether/bether/common/config/WebConfigProperties.java
  backend/src/main/resources/application.yml
Labels: ✨ feat, BE

#185 시간 유효성 검사 추가
  frontend/package.json
  frontend/src/components/Sections/BasicSettings/BasicSettings.stories.tsx
  frontend/src/components/Sections/BasicSettings/index.tsx
  frontend/src/components/Sections/OptionSettings/index.tsx
  frontend/src/hooks/useCreateRoom.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/utils/Time/checkTimeRangeValid.ts
Labels: ✨ feat, FE

#197 페이지 이동시, sessionID 기반 api 호출
  frontend/src/apis/common/baseFetch.ts
  frontend/src/apis/room/type.ts
  frontend/src/apis/transform/fromParseRoomInfo.ts
  frontend/src/apis/transform/toCreateRoomInfo.ts
  frontend/src/constants/initialRoomInfo.ts
  frontend/src/hooks/common/useExtractQueryParam.ts
  frontend/src/hooks/useCheckRoomSession.ts
  frontend/src/hooks/useCreateRoom.ts
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/pages/CreateEventPage.tsx
  frontend/src/types/roomInfo.ts
Labels: ✨ feat, FE

#195 User 엔티티와 DB 테이블 컬럼 매핑 오류
  backend/src/main/java/com/bether/bether/user/domain/User.java
Labels: 🛠 fix, BE

#192 마감기한 안내 UI 추가 및 디폴트 시간 설정
  frontend/src/components/Button/index.tsx
  frontend/src/components/Information/Information.styled.ts
  frontend/src/components/Information/index.tsx
  frontend/src/constants/initialRoomInfo.ts
  frontend/src/icons/IInfo.tsx
  frontend/src/pages/CreateEventPage.tsx
  frontend/src/styles/index.css
  frontend/src/utils/getDefaultDeadLine.ts
Labels: ✨ feat, FE

#198 RecommendTime(추천시간대) 컴포넌트 구현
  frontend/src/apis/room/room.ts
  frontend/src/apis/time/time.ts
  frontend/src/components/RecommendTime/index.tsx
Labels: ✨ feat, FE

#165 타임테이블 구현
  frontend/src/apis/time/time.ts
  frontend/src/apis/transform/fromParseRoomInfo.ts
  frontend/src/apis/transform/toCreateUserAvailablity.ts
  frontend/src/components/Layout/Wrapper/Wrapper.styled.ts
  frontend/src/components/Layout/Wrapper/index.tsx
  frontend/src/components/Timetable/Timetable.styled.ts
  frontend/src/components/Timetable/index.tsx
  frontend/src/constants/initialRoomInfo.ts
  frontend/src/hooks/TimeTable/useTimeSelection.ts
  frontend/src/hooks/useCheckRoomSession.ts
  frontend/src/hooks/useUserAvailablity.ts
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/types/roomInfo.ts
  frontend/src/types/userAvailability.ts
  frontend/src/utils/Calendar/generateTimeList.ts
  frontend/src/utils/Calendar/getDayofWeek.ts
Labels: ✨ feat, FE

#211 Room 엔티티의 StartTime, EndTime 검증 및 필드 명 수정
  backend/src/main/java/com/bether/bether/room/domain/Room.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomControllerSpecification.java
  backend/src/test/java/com/bether/bether/room/application/service/RoomApplicationServiceTest.java
Labels: 🛠 fix, BE

#216 이벤트 페이지 레이아웃 작업
  frontend/src/apis/room/room.ts
  frontend/src/components/CheckEventPageHeader/index.tsx
  frontend/src/components/LoginSuggestModal/index.tsx
  frontend/src/components/RecommendTime/RecommendTime.styled.ts
  frontend/src/components/RecommendTime/index.tsx
  frontend/src/components/Timetable/Timetable.styled.ts
  frontend/src/components/Timetable/index.tsx
  frontend/src/hooks/Login/useUserLogin.ts
  frontend/src/hooks/useCheckRoomSession.ts
  frontend/src/hooks/useUserAvailability.ts
  frontend/src/hooks/useUserAvailablity.ts
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/styles/theme.ts
Labels: FE

#225 Slack Ephemeral Message 전송 로직 수정
  backend/src/main/java/com/bether/bether/connection/slack/application/util/SlackMessageBuilder.java
  backend/src/main/java/com/bether/bether/connection/slack/infrastructure/SlackMessageSender.java
Labels: 🛠 fix, BE

#226 checkEventPage API 호출 로직 수정
  frontend/src/apis/transform/toCreateUserAvailablity.ts
  frontend/src/components/Timetable/Timetable.styled.ts
  frontend/src/components/Timetable/index.tsx
  frontend/src/hooks/Login/useUserLogin.ts
  frontend/src/hooks/useUserAvailability.ts
  frontend/src/pages/CheckEventPage.tsx
Labels: 🛠 fix, FE, 🚨 hotfix

#224 추천 시간대 api 연결
  frontend/src/apis/time/type.ts
  frontend/src/components/RecommendTime/index.tsx
  frontend/src/hooks/RecommendTime/useRecommendTime.ts
  frontend/src/pages/CheckEventPage.tsx
Labels: ✨ feat, FE

#234 사용자 제출 시간 수정 API response 수정
  backend/src/main/java/com/bether/bether/datetimeslot/application/service/DateTimeSlotService.java
  backend/src/main/java/com/bether/bether/room/application/service/RoomApplicationService.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomController.java
  backend/src/main/java/com/bether/bether/room/presentation/RoomControllerSpecification.java
  backend/src/main/java/com/bether/bether/room/presentation/dto/response/TotalDateTimeSlotUpdateResponse.java
Labels: ✨ feat, BE

#233 JDA Listener, Registrar 등록 문제 해결
  backend/src/main/java/com/bether/bether/connection/discord/config/DiscordConfig.java
  backend/src/main/java/com/bether/bether/connection/discord/config/DiscordJdaInitializer.java
  backend/src/main/java/com/bether/bether/connection/discord/infrastructure/DiscordMessageSender.java
  backend/src/main/java/com/bether/bether/connection/discord/infrastructure/DiscordSlashCommandListener.java
  backend/src/main/java/com/bether/bether/connection/discord/infrastructure/DiscordSlashCommandRegistrar.java
Labels: 🛠 fix, BE

#236 CD 과정 중 테스트 실패 해결
  backend/src/main/java/com/bether/bether/connection/discord/infrastructure/DiscordSlashCommandListener.java
  backend/src/test/java/com/bether/bether/connection/application/ConnectedRoomApplicationServiceTest.java
Labels: 🛠 fix, BE, ✅ test

#238 index.html favicon 주소 수정
  frontend/public/index.html
Labels: 🛠 fix, FE

#240 Discord & Slack 알림 링크 접속 오류 수정 및 SlackMessageSender 빈 등록 문제 해결
  backend/src/main/java/com/bether/bether/connection/application/ConnectedRoomApplicationService.java
  backend/src/main/java/com/bether/bether/connection/application/dto/input/ConnectedRoomCreatedMessageInput.java
  backend/src/main/java/com/bether/bether/connection/slack/application/util/SlackMessageBuilder.java
  backend/src/main/java/com/bether/bether/connection/slack/infrastructure/SlackMessageSender.java
Labels: 🛠 fix, BE

#246 QA 긴급 수정
  frontend/src/apis/common/baseFetch.ts
  frontend/src/apis/transform/fromParseRoomInfo.ts
  frontend/src/components/Button/Button.styled.ts
  frontend/src/components/Button/index.tsx
  frontend/src/components/CheckEventPageHeader/index.tsx
  frontend/src/components/LoginModal/index.tsx
  frontend/src/components/Modal/FocusTrap.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/RecommendTime/index.tsx
  frontend/src/components/Timetable/index.tsx
  frontend/src/constants/optionsettings.ts
  frontend/src/hooks/Login/useUserLogin.ts
  frontend/src/hooks/RecommendTime/useRecommendTime.ts
  frontend/src/pages/CheckEventPage.tsx
  frontend/src/utils/Time/add30Minutes.ts
Labels: FE, 🚨 hotfix

#264 태그 매니저 설정
  frontend/public/index.html
Labels: ✨ feat, FE

#266 remove: 불필요 yml 제거
  buildspec.yml
  frontend/buildspec.yml
Labels: FE, ♻️ refactor

#273 fix: dateTimeSlots 로 타입 변경
  frontend/src/apis/time/type.ts
  frontend/src/hooks/useUserAvailability.ts
Labels: 🛠 fix, FE
